site_name: Documentació tècnica CatSalut
site_description: Documents transversals de l'oficina d'Arquitectura del CatSalut
plugins:
  - techdocs-core
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.superfences
  pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Getting Started: index.md
  - Mermaid sample: sample-mermaid.md
  - Mapa d'aplicacions: mapa-aplicacions.md
