site_name: Documentació tècnica CatSalut
site_description: Documents transversals de l'oficina d'Arquitectura del CatSalut
plugins:
  - techdocs-core
  - kroki
nav:
  - Getting Started: index.md
  - Mermaid sample: sample-mermaid.md
  - Mapa d'aplicacions: mapa-aplicacions.md
